add Jenkinsfile, pipline

diff --git a/pipeline-err-status b/pipeline-err-status
--- a/pipeline-err-status
+++ b/pipeline-err-status
@@ -9,27 +9,33 @@ pipeline {
     stages {
         stage('Check Apache Logs') {
             steps {
-                script {
-                    // Define the log file path
-                    def logFile = ''
-                    def logFileDeb = '/var/log/apache2/access.log'
-                    def logFileRhn = '/var/log/httpd/access_log'
+                // Check for 4xx and 5xx errors
+                sh """
+                    # Define the log file path
+                    logFile=''
+                    logFileDeb='/var/log/apache2/access.log'
+                    logFileRhn='/var/log/httpd/access_log'
 
-                    // Check for 4xx and 5xx errors
-                    sh """
-                        if [ -f ${logFileDeb} ]; then
-                            logFile=${logFileDeb}
-                        elif [ -f ${logFileRhn} ]; then
-                            logFile=${logFileRhn}
-                        else
-                            echo "Log file does not exist!"
-                            exit 1
-                        fi
-                        
-                        echo "Checking for 4xx and 5xx errors in ${logFile}..."
-                        grep -E '" [45][0-9]{2} ' ${logFile} || echo "No 4xx/5xx errors found."
-                    """
-                }
+                    if [ -f "\${logFileDeb}" ]; then
+                        logFile="\${logFileDeb}"
+                    elif [ -f "\${logFileRhn}" ]; then
+                        logFile="\${logFileRhn}"
+                    else
+                        echo "Log file does not exist!"
+                        exit 1
+                    fi
+
+                    echo "Checking for 4xx and 5xx errors in \${logFile}..."
+                    ERRORS=\$(grep -E ' [45][0-9]{2} ' "\${logFile}" 2>&1 || true)
+
+                    if [ -z "\${ERRORS}" ]; then
+                        echo "No 4xx/5xx errors found."
+                    else
+                        echo "Found the following 4xx/5xx errors:"
+                        echo "\${ERRORS}" | head -n 10
+                        exit 1
+                    fi                     
+                """
             }
         }
     }
